### ISSUE TITLE
Pedantic suggestions

### ISSUE THREAD

**Issue by dronir** [anttikon/routahe#3]
Hi, a bit of pedantry here that you can disregard if you want to.

The current output color scheme is a bit incongruous. HSL has official colors for the different transport modes (https://www.hsl.fi/tyyliopas/varit): blue for buses, green for tram, orange for metro, purple for train, and lightblue for ferry (walking isn't mentioned, but seems to be just grey in Reittiopas).

Second, the Helsinki metro is called "metro" in English, not "subway".

**Comment by anttikon** [comment]
Hi!

Your suggestion about the color scheme seems reasonable. Unfortunately ANSI contains only [eight standard colors](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors).

However I changed the color scheme a bit as you can see in 9bdde59df3defb6a0ab6f1cc745e60ba46ffb932. I think that the new color scheme is as close to official color scheme as possible. For an example tram does really _feel_ green.

And metro is metro indeed! In fact Routahe gets the term "subway" straight from the HSL API, so for now I wouldn't change it but I'll definitely consider the issue!

🚌💨
